# Generated by Django 4.1.7 on 2023-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phno', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('account', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
    ]
