# Generated by Django 4.0.4 on 2023-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
